version: '2'

services:
  initiator:
    build: .
    image: gabrielkulp/bls:latest
    command: "./server.py ${SERVER_COUNT:-10} ${THRESHOLD:-7} ${RUNTIME:-30}"
    networks:
      bls-net:
        ipv4_address: 10.0.0.254

  responder:
    build: .
    image: gabrielkulp/bls:latest
    command: "./restart.py ${SERVER_COUNT:-10} ${THRESHOLD:-7} ${RUNTIME:-30} ${ATTACKTIME:-10} ${REBOOTTIME:-3}"
    depends_on:
      - initiator
    deploy:
      replicas: "${SERVER_COUNT:-10}"
    networks:
      bls-net:

networks:
  bls-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1

