version: '2'

services:
  initiator:
    build: .
    image: gabrielkulp/bls:latest
    command: [ "./server.py", "10", "7", "20" ]
    #"${SERVER_COUNT:-10}" "${THRESHOLD:-7}"
    networks:
      bls-net:
        ipv4_address: 10.0.0.254

  responder:
    build: .
    image: gabrielkulp/bls:latest
    #command: [ "./server.py" ]
    command: [ "./restart.py", "10", ".7", "8", "2", "20" ]
    depends_on:
      - initiator
    deploy:
      replicas: 10
      # replicas: "${SERVER_COUNT:-10}"
    networks:
      bls-net:

networks:
  bls-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1

